server:
  port: 8181


spring:
  datasource:
    name: miaosha
    password: pass
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncodeing=utf-8&serverTimezone=GMT&2b88&useSSL=false&allowPublicKeyRetrieval=true

logging:
  level:
    root: info
    com.spj.miaosha.dao: debug

mybatis:
#  映射文件路径 在resource文件夹下用classpath：表示
  mapper-locations: classpath:mapper/*.xml
